name: End to End Integration Tests

on:
  pull_request:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  test-action:
    name: E2E Action Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action With All Files Ignored
        id: all_files_ignored
        uses: ./
        with:
          always-succeed-before-approval: false
          codeowners-path: MISSING_CODEOWNERS
          ignore-filepaths: '*'

      - name: Test Local Action With Missing Codeowners File
        id: missing_codeowners
        continue-on-error: true
        uses: ./
        with:
          always-succeed-before-approval: false
          codeowners-path: MISSING_CODEOWNERS

      - name: Fail if missing_codeowners succeeded
        if: steps.missing_codeowners.outcome == 'success'
        run: |
          echo "Error: missing_codeowners should have failed but succeeded" && exit 1

      - name: Test Local Action With Current User ignored
        id: current_user_ignored
        uses: ./
        with:
          always-succeed-before-approval: false
          codeowners-path: MISSING_CODEOWNERS
          ignore-authors: ${{ github.event.pull_request.user.login }}

      - name: Test Local Action With Current User is Owner
        id: current_user_is_owner
        uses: ./
        with:
          always-succeed-before-approval: false
          codeowners-contents: |
            *. @fakeorg/faketeam
            * @${{ github.event.pull_request.user.login }}

  test-action-pr-review:
    name: E2E Action Tests PR Review Event
    runs-on: ubuntu-latest
    # prettier-ignore
    if: >-
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'APPROVED'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Test Local Action Where Current Approver is Owner
        id: current_approver_is_owner
        uses: ./
        with:
          codeowners-contents: |
            * @fakeorg/faketeam
            * @${{ github.event.review.user.login }}

      - name: Test Local Action Where Current Approver is Not Owner
        id: current_approver_is_not_owner
        uses: ./
        continue-on-error: true
        with:
          codeowners-contents: |
            *.ts @fakeorg/faketeam

      - name: Fail if current_approver_is_not_owner succeeded
        if: steps.current_approver_is_not_owner.outcome == 'success'
        run: |
          echo "Error: current_approver_is_not_owner should have failed but succeeded" && exit 1
